apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-prod-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: git@github.com:your-org/argocd-applicationset-config.git
        revision: main
        directories:
          - path: "prod/*"
  template:
    metadata:
      name: "{{path.basename}}-{{name}}"  # Example: prod-service1, prod-dr-service2
    spec:
      project: prod
      source:
        repoURL: "{{repo}}"
        targetRevision: main
        path: "./"
        helm:
          valueFiles:
            - "values-{{path.basename}}.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

