apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/savinp/argocd-applicationset-config
        revision: develop
        files:
          - path: config
  template:
    metadata:
      name: '{{env}}-{{name}}'
    spec:
      destination:
        namespace: '{{env}}'
        server: https://kubernetes.default.svc
      project: default
      source:
        repoURL: '{{repoURL}}'
        path: ./
        targetRevision: main
        helm:
          valueFiles:
            - values.yaml
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
