apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices-nonprod-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/savinp/argocd-applicationset-config
        revision: develop
        directories:
          - path: "non-prod/*"
  template:
    metadata:
      name: "{{path.basename}}-{{name}}"  # Example: dev-service1, staging-service2
    spec:
      project: non-prod
      source:
        repoURL: "{{repo}}"
        targetRevision: main
        path: "./"
        helm:
          valueFiles:
            - "values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true

